// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmhjH8HS3yHwwoZ9qCSKyNPCR5XRVxTI',
    appId: '1:513072589861:web:9168cf06b3bda7bbbce3cc',
    messagingSenderId: '513072589861',
    projectId: 'crystal-grimoire-2025',
    authDomain: 'crystal-grimoire-2025.firebaseapp.com',
    storageBucket: 'crystal-grimoire-2025.firebasestorage.app',
    measurementId: 'G-LMQRB8LVYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__1EHCjv9pCRJzQoRQiKVxTfaPMXFXAs',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'crystal-grimoire-2025',
    storageBucket: 'crystal-grimoire-2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__1EHCjv9pCRJzQoRQiKVxTfaPMXFXAs',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'crystal-grimoire-2025',
    storageBucket: 'crystal-grimoire-2025.appspot.com',
    iosBundleId: 'com.crystalgrimoire.fresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC__1EHCjv9pCRJzQoRQiKVxTfaPMXFXAs',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'crystal-grimoire-2025',
    storageBucket: 'crystal-grimoire-2025.appspot.com',
    iosBundleId: 'com.crystalgrimoire.fresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC__1EHCjv9pCRJzQoRQiKVxTfaPMXFXAs',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'crystal-grimoire-2025',
    authDomain: 'crystal-grimoire-2025.firebaseapp.com',
    storageBucket: 'crystal-grimoire-2025.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
}